---
# defaults file for bbaassssiiee.openebs
helm_binary: /usr/local/bin/helm
helm_repo_name: openebs
helm_repo_url: https://openebs.github.io/openebs
helm_chart_name: openebs
ebs_namespace: openebs
desired_state: true

openebs_release_values:
  openebs-crds.csi.volumeSnapshots.enable: false
  engines:
    local:
      lvm:
        enabled: true
      zfs:
        enabled: false
    replicated:
      mayastor:
        enabled: false

base_path: /var/openebs/local
mount_path: /mnt/openebs-local
# values
